// src/utils/synonyms.js
//
// A small, hand-picked synonym table for the client-side paraphraser in
// paraphrase.js. This is intentionally NOT a full thesaurus -- it's a few
// hundred common English words (adjectives, adverbs, verbs, nouns) mapped to
// one plain-English replacement each. One replacement per word (rather than a
// list) keeps output deterministic, which is what makes it testable and what
// keeps the cache in CacheContext meaningful (same input -> same output).
//
// Lookup is case-insensitive; the paraphraser re-applies the original casing
// after substitution (see applyCase in paraphrase.js).
export const SYNONYMS = {
  // --- adjectives: size / degree ---
  big: "large",
  small: "little",
  huge: "enormous",
  tiny: "minuscule",
  great: "excellent",
  good: "solid",
  bad: "poor",
  nice: "pleasant",
  important: "significant",
  minor: "small",
  major: "substantial",
  easy: "simple",
  hard: "difficult",
  difficult: "challenging",
  simple: "straightforward",
  complex: "intricate",
  complicated: "convoluted",
  fast: "rapid",
  quick: "speedy",
  slow: "sluggish",
  smart: "intelligent",
  clever: "ingenious",
  wise: "sensible",
  happy: "joyful",
  sad: "unhappy",
  angry: "irritated",
  afraid: "fearful",
  tired: "exhausted",
  bored: "uninterested",
  excited: "thrilled",
  calm: "relaxed",
  nervous: "anxious",
  confident: "self-assured",
  strong: "powerful",
  weak: "feeble",
  new: "recent",
  old: "outdated",
  young: "youthful",
  modern: "contemporary",
  ancient: "age-old",
  clean: "tidy",
  dirty: "grimy",
  cheap: "inexpensive",
  expensive: "costly",
  rich: "wealthy",
  poor: "impoverished",
  beautiful: "gorgeous",
  pretty: "attractive",
  ugly: "unattractive",
  interesting: "engaging",
  boring: "dull",
  funny: "amusing",
  serious: "grave",
  strange: "unusual",
  common: "typical",
  rare: "uncommon",
  useful: "helpful",
  useless: "pointless",
  safe: "secure",
  dangerous: "hazardous",
  correct: "accurate",
  wrong: "incorrect",
  true: "accurate",
  false: "untrue",
  possible: "feasible",
  impossible: "unattainable",
  necessary: "essential",
  obvious: "evident",
  clear: "apparent",
  confusing: "perplexing",
  reliable: "dependable",
  flexible: "adaptable",
  efficient: "effective",
  powerful: "forceful",
  popular: "well-liked",
  famous: "renowned",
  unknown: "unfamiliar",
  perfect: "flawless",
  broken: "damaged",
  empty: "vacant",
  full: "complete",
  early: "premature",
  late: "delayed",
  loud: "noisy",
  quiet: "silent",
  bright: "vivid",
  dark: "dim",
  heavy: "weighty",
  light: "lightweight",
  thick: "dense",
  thin: "slender",
  wide: "broad",
  narrow: "tight",
  deep: "profound",
  shallow: "superficial",
  soft: "gentle",
  rough: "coarse",
  smooth: "even",
  sharp: "keen",
  dull: "blunt",

  // --- adverbs / intensifiers ---
  very: "extremely",
  really: "genuinely",
  quite: "fairly",
  extremely: "exceptionally",
  totally: "completely",
  absolutely: "utterly",
  probably: "likely",
  definitely: "certainly",
  usually: "typically",
  often: "frequently",
  rarely: "seldom",
  sometimes: "occasionally",
  always: "consistently",
  never: "at no point",
  slowly: "gradually",
  quickly: "rapidly",
  easily: "effortlessly",
  suddenly: "abruptly",
  finally: "ultimately",
  currently: "presently",
  recently: "lately",
  immediately: "instantly",
  eventually: "in time",
  clearly: "plainly",
  obviously: "evidently",
  actually: "in fact",
  basically: "fundamentally",
  literally: "exactly",
  simply: "merely",
  mostly: "mainly",
  generally: "broadly",
  especially: "particularly",

  // --- verbs: everyday actions ---
  make: "create",
  build: "construct",
  get: "obtain",
  give: "provide",
  take: "grab",
  show: "display",
  tell: "inform",
  ask: "request",
  say: "state",
  think: "believe",
  know: "understand",
  want: "desire",
  need: "require",
  use: "utilize",
  find: "discover",
  help: "assist",
  start: "begin",
  stop: "halt",
  finish: "complete",
  keep: "retain",
  try: "attempt",
  change: "modify",
  improve: "enhance",
  reduce: "decrease",
  increase: "raise",
  add: "append",
  remove: "eliminate",
  fix: "repair",
  break: "damage",
  move: "relocate",
  send: "dispatch",
  receive: "obtain",
  buy: "purchase",
  sell: "market",
  pay: "compensate",
  save: "preserve",
  spend: "expend",
  learn: "study",
  teach: "instruct",
  explain: "clarify",
  describe: "depict",
  discuss: "debate",
  decide: "determine",
  choose: "select",
  agree: "concur",
  disagree: "differ",
  suggest: "propose",
  recommend: "advise",
  allow: "permit",
  prevent: "avert",
  cause: "trigger",
  affect: "influence",
  focus: "concentrate",
  continue: "proceed",
  begin: "commence",
  end: "conclude",
  return: "come back",
  arrive: "reach",
  leave: "depart",
  enter: "access",
  create: "produce",
  design: "craft",
  develop: "cultivate",
  handle: "manage",
  solve: "resolve",
  understand: "grasp",
  remember: "recall",
  forget: "overlook",
  notice: "observe",
  realize: "recognize",
  ensure: "guarantee",
  provide: "supply",
  offer: "extend",
  require: "necessitate",
  include: "incorporate",
  exclude: "omit",
  combine: "merge",
  separate: "divide",
  connect: "link",
  support: "back",
  reveal: "expose",
  hide: "conceal",

  // --- nouns: general ---
  idea: "concept",
  problem: "issue",
  solution: "resolution",
  result: "outcome",
  reason: "rationale",
  goal: "objective",
  plan: "strategy",
  method: "approach",
  process: "procedure",
  system: "framework",
  project: "initiative",
  task: "assignment",
  job: "occupation",
  work: "labor",
  team: "group",
  company: "organization",
  business: "enterprise",
  customer: "client",
  product: "offering",
  service: "provision",
  feature: "capability",
  benefit: "advantage",
  issue: "concern",
  risk: "hazard",
  chance: "opportunity",
  choice: "option",
  effect: "impact",
  example: "instance",
  detail: "specific",
  information: "data",
  question: "query",
  answer: "response",
  opinion: "viewpoint",
  fact: "truth",
  story: "narrative",
  event: "occurrence",
  situation: "circumstance",
  condition: "state",
  level: "degree",
  amount: "quantity",
  number: "figure",
  price: "cost",
  value: "worth",
  quality: "caliber",
  time: "duration",
  place: "location",
  area: "region",
  world: "globe",
  people: "individuals",
  person: "individual",
  child: "kid",
  friend: "companion",
  family: "household",
  money: "funds",
  power: "authority",
  control: "command",
  knowledge: "expertise",
  skill: "ability",
  experience: "background",
  history: "past",
  future: "prospect",
  law: "regulation",
  rule: "guideline",
  right: "entitlement",
  freedom: "liberty",
  health: "wellbeing",
  environment: "surroundings",
  technology: "tech",
  science: "research",
  education: "schooling",
  government: "administration",
  community: "populace",
  culture: "heritage",
  society: "populace",
  economy: "marketplace",
  market: "marketplace",
  industry: "sector",
};

// Words that carry little meaning on their own and read as padding once the
// sentence has been substituted -- e.g. "I basically just really wanted to
// know" -> "I wanted to know". Trimmed as whole words only (see
// stripFillerWords in paraphrase.js), never mid-word.
export const FILLER_WORDS = [
  "basically",
  "actually",
  "literally",
  "really",
  "just",
  "very",
  "quite",
  "simply",
  "honestly",
  "essentially",
  "virtually",
  "practically",
  "kind of",
  "sort of",
  "you know",
  "i mean",
  "in fact",
];
